### DISCUSSION TITLE
Problems with Snap package application

### DISCUSSION THREAD

**Discussion by pzs-scnu** [AvaloniaUI/Avalonia#15245] [Q&A]
I build a dotnet application with Avalonia 11.0.9, the app runs OK in Rider IDE or in terminal, but when I build a snap package with snapcraft, the content of my snapcraft.yaml is:
```
name: musicfans  # name must be lowercase
version: '2.5.0'
summary: An audio player that can play most commonly used audio files.
# | is a multiline string indicator
description: |
 play most commonly used audio files like flac, ape, wav, wv, tta, m4a, ogg, aiff, aac, dsf, dff, support DSD PCM and DoP play mode, edit audio file meta info like album title, track title, performer, artist, artwork, extract audio files to flac, wav, ogg from audio CD, convert audio file. 
# base is the snapcraft plugin to use
base: core22
# confinement level of the snap
confinement: strict
# grade level of the snap, can be devel, stable, or edge
grade: stable
# apps section is where you define the command that will be used to run your application
apps:
  musicfans:
    # command to run the application
    command: MusicFans.Linux
    # desktop file to use for the application
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - unity7
      - wayland
      - pulseaudio
      - gsettings
      - network
      - network-bind
      - audio-playback
      - removable-media
# parts section is where you define the parts that make up your snap
parts:
  musicfans:
    # plugin to use for this part, in this case, the dotnet plugin
    plugin: dotnet
    # source of the project, in this case, the current directory
    source: MusicFans.Linux
    # build packages needed to build the project, in this case, the dotnet-sdk-7.0 package
    override-build: |
     dotnet build MusicFans.Linux.csproj -c Release
     dotnet publish MusicFans.Linux.csproj -r linux-x64 -c Release -p:PublishSingleFile=true --self-contained true -f net7.0 -o $SNAPCRAFT_PART_INSTALL
     chmod 0755 $SNAPCRAFT_PART_INSTALL/MusicFans.Linux
    # build packages needed to build the project, in this case, the dotnet-sdk-7.0 package
    build-packages:
      - dotnet-sdk-7.0
    stage-packages:
      - libicu70
      - libfontconfig1
      - libx11-6
      - libice6
      - libsm6
    # runtime packages needed to run the project, in this case, the dotnet-runtime-7.0 package
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
```

install the app by command:
sudo snap install musicfans_2.5.0_amd64.snap --devmode --dangerous

when I run the app by command(snap package name): musicfans, the app can show its UI, but when I right click the mouse, the context menu can not be shown, and the app can not write file to System.Environment.SpecialFolder.UserProfile directory.
the app is fully functional when I run the executable file in terminal directly: MusicFans.Linux (I've add PATH to the snap package install directory: /snap/musicfans/x1)
I know the snap package is sandboxed, but how can I make the app fully functional in snap package?
