### DISCUSSION TITLE
Deserialization does not bind to the ComboBox.

### DISCUSSION THREAD

**Discussion by Ha-rlan** [AvaloniaUI/Avalonia#18010] [Q&A]
When I use a ComboBox bound to an ObservableCollection<ReplyUnit>, where ReplyUnit contains another object Data, my ComboBox binding is written as follows:
```axaml
     <ComboBox ItemsSource="{Binding $parent[UserControl].((vm:ProtocolSettingViewModel)DataContext).Protocol.FunctionMap}"
                                                          SelectedValue="{Binding Data}" Width="100" DisplayMemberBinding="{Binding DisplayText}"/>
```
When I select an item, it works well, and I save the object to a YAML file using YamlDotNet：
```yaml
flagIndex: 1
FunctionMap:
- &o1
  DataUnits:
  - Type: Flag
    Default: 01
    Length: 1
  DisplayText: 01
- &o0
  DataUnits:
  - Type: Flag
    Default: 01
    Length: 1
  - Type: Mock
    Default: 
    Length: 4
  DisplayText: 01
ResponseMap:
- Cases:
  - Protocols:
    - DataUnits:
      - Type: Flag
        Default: 01
        Length: 1
      DisplayText: 01
    Enabled: true
    Description: 测试Case
  Name: 
  Flag: 2
  Data: *o0
  IsActive: true
  Strategy: Order
- Cases:
  - Protocols:
    - DataUnits:
      - Type: Flag
        Default: 01
        Length: 1
      - Type: Mock
        Default: 
        Length: 4
      DisplayText: 01
    Enabled: true
    Description: 测试Case
  Name: 
  Flag: 3
  Data: *o1
  IsActive: true
  Strategy: Order
 ```
But when I deserialize, the content of the ComboBox in the interface is empty, and I'm not sure why this is happening.
