### ISSUE TITLE
Support Multiple Selectors for Styles

### ISSUE THREAD

**Issue by grapehunter** [AvaloniaUI/Avalonia#1742]
In css, we can use Multiple Selector like this
```css
button,.test{
    color:red;
}
```
Can we use it in avalonia?
I have tried Selector= `a,b`,`a|b`,`a||b`,`a;b`, and they are all not work
