### ISSUE TITLE
Deploy an Avalonia app using Flatpack

### ISSUE THREAD

**Issue by aboimpinto** [AvaloniaUI/Avalonia#5125]
Hello,

I'm focused on developing, primarily, for Linux distributions, and Avalonia looks like it's a perfect match because I see myself as a XAML developer.

I develop a simple Avalonia app and used the guide to create Flatpack for .NET Core apps 
https://www.phillipsj.net/posts/packaging-dotnet-core-with-flatpak/

I'm not sure about all the steps, but when I try to run the build (before publishing the package), the app doesn't run and doesn't even give me an error message.

I think the problem is the guide is for the console applications, and Avalonia it's a GUI app, which means the step where we create the metadata for the Flatpack maybe is the right one.

Doesn't anyone was able to create a FlatPack package for their  Avalonia app on Linux?

Thanks
Paulo Aboim Pinto

**Comment by kekekeks** [comment]
1) don't use warp or other "single binary" solutions, those are blatant lies. Just publish with `dotnet publish -r linux-x64`
2) IIRC due to some Skia/libfontconfig bug Skia fails to load *any* system fonts on certain Linux installations (https://github.com/AvaloniaUI/Avalonia/issues/4427). That's usually fixed by installing mscorefonts, not sure how to include those in flatpak

**Comment by aboimpinto** [comment]
I don't know if I understand everything you said ... 
right now was just an experience to know if it's possible and I'm sure there will be a way to do it. If there is no recipe to do It, I will figure it out in the future. Maybe then someone already creates a guide to explain how to do it.

**Comment by sakya** [comment]
This works for me:
- Build your application
  `dotnet publish solution.sln -c Release --runtime linux-x64 -p:PublishReadyToRun=true --self-contained --output ./dist/linux-x64`
- Manifest
  ```
  app-id: org.flatpak.appName
  runtime: org.freedesktop.Platform
  runtime-version: '21.08'
  sdk: org.freedesktop.Sdk
  command: appCommand
  modules:
    - name: appName
      buildsystem: simple
      build-commands:
        - cp -r . /app/bin
      sources:
        - type: dir
          path: /path/dist/linux-x64/
  finish-args:      
    - --socket=x11
    - --socket=wayland
  ```
